version: "3.3"
services:
  postgres:
    container_name: postgres_node
    image: postgres:13
    environment:
      - POSTGRES_DB=${NODE_DB_NAME}
      - POSTGRES_USER=${NODE_DB_USER}
      - POSTGRES_PASSWORD=${NODE_DB_PASSWORD}
    ports:
      - ${NODE_DB_PORT}:${NODE_DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_node
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${NODE_PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${NODE_PG_PASSWORD}
    ports:
      - ${NODE_PG_PORT}:80
